include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_return: error
    dead_code: error
    unused_local_variable: error
    unused_import: error
    unnecessary_cast: error
    unused_element: error

linter:
  rules:
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    annotate_overrides: true
    avoid_dynamic_calls: true
    avoid_print: true
    avoid_returning_null: true
    avoid_returning_null_for_future: true
    avoid_types_on_closure_parameters: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_typing_uninitialized_variables: true
    type_annotate_public_apis: true
    public_member_api_docs: true
    use_key_in_widget_constructors: true
    avoid_unused_constructor_parameters: true
    no_logic_in_create_state: true
    use_build_context_synchronously: true
    await_only_futures: true
    avoid_void_async: true
    only_throw_errors: true
    avoid_web_libraries_in_flutter: true
    avoid_positional_boolean_parameters: true
    avoid_setters_without_getters: true
    sort_pub_dependencies: true
    prefer_expression_function_bodies: true
    require_trailing_commas: true
    unnecessary_this: true
