name: dh_schedule_generatorutb
description: Generador de horarios para estudiantes de UTB

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.11.1
  path_provider: ^2.0.11
  path_provider_windows: ^2.1.3
  open_file: ^3.5.6
  csv: ^5.0.0
  excel: ^2.0.0
  collection: ^1.16.0
  diacritic: ^0.1.3
  universal_html: ^2.2.4
  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Roboto-Regular.ttf

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
