name: dh_schedule_generatorutb
description: Generador de horarios para estudiantes de UTB

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Otras dependencias que uses

dev_dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pdf: ^3.6.5
  excel: ^2.0.1

flutter:
  uses-material-design: true

  # assets:
  #   - assets/ # Si tienes imágenes u otros recursos

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
