

services:
  db:
    image: postgres:15
    container_name: postgres-schedule
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - schedule-net

  backend:
    build: ./backend
    container_name: backend-schedule
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./shared_data:/app/shared_data
    networks:
      - schedule-net
    restart: "no" # Corre una vez para actualizar JSON

  api:
    build: ./api
    container_name: api-schedule
    depends_on:
      - backend
    ports:
      - "8000:8000"
    volumes:
      - ./shared_data:/app/shared_data
    networks:
      - schedule-net
    restart: always

volumes:
  postgres_data:

networks:
  schedule-net:
