// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg2sucRPk1A6gHk4Elb64btsBtmlNl9tQ',
    appId: '1:161597507125:web:25aca8d6b25e92c0f5537c',
    messagingSenderId: '161597507125',
    projectId: 'schedule-generator-utb-d1ccc',
    authDomain: 'schedule-generator-utb-d1ccc.firebaseapp.com',
    storageBucket: 'schedule-generator-utb-d1ccc.firebasestorage.app',
    measurementId: 'G-22YPEBYCYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmYWwOON6uW5a-hvXH3-A-blSnns64hAA',
    appId: '1:161597507125:android:5c61672b6e91523ef5537c',
    messagingSenderId: '161597507125',
    projectId: 'schedule-generator-utb-d1ccc',
    storageBucket: 'schedule-generator-utb-d1ccc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWxjEc8xiL8p3S77UdJetq4oEQEHqL_Ko',
    appId: '1:161597507125:ios:b77abfcf681d36c9f5537c',
    messagingSenderId: '161597507125',
    projectId: 'schedule-generator-utb-d1ccc',
    storageBucket: 'schedule-generator-utb-d1ccc.firebasestorage.app',
    iosBundleId: 'com.example.try2Schedule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWxjEc8xiL8p3S77UdJetq4oEQEHqL_Ko',
    appId: '1:161597507125:ios:b77abfcf681d36c9f5537c',
    messagingSenderId: '161597507125',
    projectId: 'schedule-generator-utb-d1ccc',
    storageBucket: 'schedule-generator-utb-d1ccc.firebasestorage.app',
    iosBundleId: 'com.example.try2Schedule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg2sucRPk1A6gHk4Elb64btsBtmlNl9tQ',
    appId: '1:161597507125:web:4cdbcef0d49be6e8f5537c',
    messagingSenderId: '161597507125',
    projectId: 'schedule-generator-utb-d1ccc',
    authDomain: 'schedule-generator-utb-d1ccc.firebaseapp.com',
    storageBucket: 'schedule-generator-utb-d1ccc.firebasestorage.app',
    measurementId: 'G-SWLZV78VKB',
  );
}
